# -*- coding: utf-8 -*-
"""make_demo_msh —— 生成 2D 通道结构网格（Fluent legacy ASCII .msh）。

用途：给真实 Fluent 冒烟/校准提供零依赖网格（40 个四边形单元，秒级求解）。

★ 格式关键（真机实测校准 2026-09-20，Fluent 2022R2）★
  - 所有整数字段（zone-id / 索引 / 数量 / 类型码）一律十六进制；
  - 节点坐标为十进制标量，2D 每节点 2 个数（ndim 字段=2）；
  - 节点/面数据体均需包裹：头部行以 "(" 结尾，数据后以 "))" 结束；
  - (45 ...) 字段序：(zone-id first last zone-type zone-name)，整数均 hex；
  - 面数据语义（elbow.msh 1300 个内部面统计实证 2026-09-20）：c0 是 (n0→n1) 行进方向【左】侧单元，c1 是右侧；边界面 c0=内部单元且在左，c1=0。

区域：inlet(x=0, velocity-inlet=24) / outlet(x=L, pressure-outlet=5) / wall(上下, 3)。
用法：python tools/make_demo_msh.py [out.msh]
"""
from __future__ import annotations

import sys
from pathlib import Path

NX, NY = 10, 4
LX, LY = 0.1, 0.01


def _parse_overrides(argv: list[str]) -> None:
    """可选 k=v 覆盖：NX NY LX LY（如 --set NX=50 LX=0.5）。"""
    global NX, NY, LX, LY
    for a in argv:
        if "=" in a:
            k, v = a.split("=", 1)
            if k in ("NX", "NY"):
                globals()[k] = int(v)
            elif k in ("LX", "LY"):
                globals()[k] = float(v)


def h(v: int) -> str:
    """Fluent .msh 整数字段一律十六进制。"""
    return format(v, "x")


def main(out: str) -> int:
    nx, ny = NX, NY
    LX, LY = globals()["LX"], globals()["LY"]
    nodes = [(i * LX / nx, j * LY / ny) for j in range(ny + 1) for i in range(nx + 1)]
    nn = len(nodes)

    def nid(i, j) -> int:  # 1-based fluent node index
        return j * (nx + 1) + i + 1

    def cid(i, j) -> int:  # 1-based fluent cell index
        return j * nx + i + 1

    interior: list[tuple[int, int, int, int]] = []
    for j in range(ny):          # 竖直面：法线 -x → c0=左格
        for i in range(1, nx):
            interior.append((nid(i, j), nid(i, j + 1), cid(i - 1, j), cid(i, j)))
    for j in range(1, ny):       # 水平面：法线 +y → c0=下格
        for i in range(nx):
            interior.append((nid(i, j), nid(i + 1, j), cid(i, j), cid(i, j - 1)))

    wall: list[tuple[int, int, int, int]] = []
    for i in range(nx):          # 底面 y=0：内部单元在左侧行走方向(+X) → 自然序
        wall.append((nid(i, 0), nid(i + 1, 0), cid(i, 0), 0))
    for i in range(nx):          # 顶面 y=LY：内部单元在左侧行走方向(−X) → 反向
        wall.append((nid(i + 1, ny), nid(i, ny), cid(i, ny - 1), 0))

    inlet: list[tuple[int, int, int, int]] = []
    for j in range(ny):          # x=0：内部单元在左侧行走方向(−Y) → 反向
        inlet.append((nid(0, j + 1), nid(0, j), cid(0, j), 0))

    outlet: list[tuple[int, int, int, int]] = []
    for j in range(ny):          # x=LX：内部单元在左侧行走方向(+Y) → 自然序
        outlet.append((nid(nx, j), nid(nx, j + 1), cid(nx - 1, j), 0))

    nc = nx * ny
    total = len(interior) + len(wall) + len(inlet) + len(outlet)

    def stream(faces: list[tuple[int, int, int, int]]) -> str:
        return "\n".join(f"{h(a)} {h(b)} {h(c)} {h(d)}" for a, b, c, d in faces)

    n_int = len(interior)
    wall_first = n_int + 1
    wall_last = n_int + len(wall)
    inlet_first = wall_last + 1
    inlet_last = wall_last + len(inlet)
    outlet_first = inlet_last + 1
    outlet_last = total

    msh = f"""(0 "aeroharness demo channel 2D (generated by tools/make_demo_msh.py)")
(2 2)
(0 "nodes:")
(10 (0 1 {h(nn)} 0 2))
(10 (1 1 {h(nn)} 1 2)(
{"".join(f"{x:.9g} {y:.9g}\n" for x, y in nodes)}))
(0 "cells:")
(12 (0 1 {h(nc)} 0))
(12 ({h(1000)} 1 {h(nc)} 1 3))
(0 "faces:")
(13 (0 1 {h(total)} 0))
(13 (2 1 {h(n_int)} 2 2)(
{stream(interior)}
))
(13 (3 {h(wall_first)} {h(wall_last)} 3 2)(
{stream(wall)}
))
(13 (4 {h(inlet_first)} {h(inlet_last)} {h(24)} 2)(
{stream(inlet)}
))
(13 (5 {h(outlet_first)} {h(outlet_last)} 5 2)(
{stream(outlet)}
))
(0 "zone names:")
(45 (2 interior interior-2)())
(45 (3 wall wall-3)())
(45 (4 velocity-inlet inlet)())
(45 (5 pressure-outlet outlet)())
(45 (1000 fluid fluid-1000)())
"""

    out_p = Path(out)
    out_p.parent.mkdir(parents=True, exist_ok=True)
    out_p.write_text(msh, encoding="utf-8")
    print(f"written {out_p}: nodes={nn} cells={nc} faces={total} "
          f"(interior={n_int} wall={len(wall)} inlet={len(inlet)} outlet={len(outlet)})")
    return 0


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "meshes/channel2d.msh"
    _parse_overrides(sys.argv[2:])
    raise SystemExit(main(out))
